root: true
extends:
  - airbnb

plugins:
  - react
  - jest

rules:
  arrow-parens:
    - warn
    - always
  react/jsx-filename-extension: off
  react/react-in-jsx-scope: off
  react/self-closing-comp: off
  react/function-component-definition:
    - 2
    - namedComponenets: function-declaration